name: XNU CodeQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        macos-version: [ 'macOS 13.0', 'macOS 13.1', 'macOS 13.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deps
        run: |
          brew update
          brew install bash

      - name: kmutil help # This is to check for what flags are available
        run: |
          sysctl -n kern.bootobjectspath || true
          kmutil inspect
          kmutil create --help

      - name: Build XNU JSON compilation database
        run: |
          XNU_VERSION='${{ matrix.macos-version }}' MACHINE_CONFIG=T6000 JSONDB=1 bash build.sh

      - name: Build XNU
        run: XNU_VERSION='${{ matrix.macos-version }}' MACHINE_CONFIG=T6000 bash build.sh --kc

      - uses: actions/upload-artifact@v3
        with:
          name: xnu-build-${{ matrix.macos-version }}
          path: |
            fakeroot/System/Library/Kernels/
            fakeroot/oss-xnu.kc

      - name: Build XNU CodeQL Database
        run: XNU_VERSION='${{ matrix.macos-version }}' MACHINE_CONFIG=T6000 bash codeql.sh

      - uses: actions/upload-artifact@v3
        with:
          name: xnu-codeql-${{ matrix.macos-version }}
          path: xnu-codeql.zip